services:
  mongo:
    image: mongo:7
    container_name: adl-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: adl
    volumes:
      - adl_mongo_data:/data/db

volumes:
  adl_mongo_data:
